# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHRG0MfqbIB2GPc60gDvUXuSNoGfum0J
"""

import numpy as np

# Create a 4x4 array from an exponential distribution
# The 'scale' parameter (beta) is set to 1.0 by default, which is lambda = 1.
# You can adjust 'scale' if a different rate parameter is needed.
exponential_array = np.random.exponential(scale=1.0, size=(4, 4))

print("Random 4x4 array from an exponential distribution:")
print(exponential_array)

import numpy as np
import matplotlib.pyplot as plt

# 1. Create a random 100000x1 array from the exponential distribution
# Using the same scale=1.0 as the previous task
exponential_data = np.random.exponential(scale=1.0, size=100000)

# 2. Create a random 100000x1 array from the uniform distribution
uniform_data = np.random.rand(100000) # This generates data between 0 and 1

# 3. Create a random 100000x1 array from the normal distribution
normal_data = np.random.randn(100000) # Standard normal distribution (mean=0, std=1)

# Plotting the histograms
plt.figure(figsize=(10, 6))

# Exponential Distribution
plt.hist(exponential_data, density=True, bins=200, histtype="step", color="red", label="Exponential")

# Uniform Distribution
plt.hist(uniform_data, density=True, bins=100, histtype="step", color="blue", label="Uniform")

# Normal Distribution
plt.hist(normal_data, density=True, bins=200, histtype="step", color="green", label="Normal")

# Adjusting plot view
plt.axis([-4, 8, 0, 1.2]) # Adjusted x-axis to cover the range of exponential and normal data, y-axis for density
plt.legend(loc="upper right") # Moved legend to avoid overlap with density peaks
plt.title("Random Distributions")
plt.xlabel("Value")
plt.ylabel("Density")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Define the range for X and Y
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

# Create a meshgrid for X and Y
X, Y = np.meshgrid(x, y)

# Calculate Z based on the function Z = X**2 + Y**2
Z = X**2 + Y**2

# Create a 3D plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
ax.plot_surface(X, Y, Z, cmap='viridis')

# Set labels and title
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.set_zlabel('Z-axis')
ax.set_title('3D Plot of Z = X^2 + Y^2')

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# --- IMPORTANT ---
# As no specific dataset was provided for the 'seaborn tutorial.ipynb',
# I am creating a synthetic DataFrame for demonstration purposes.
# If you have an existing DataFrame, please replace this section with your actual data loading.
# Make sure your DataFrame 'df' contains columns like 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed'.

# Synthetic data creation (replace with your actual data loading)
np.random.seed(42) # for reproducibility
data = {
    'HP': np.random.randint(10, 200, 100),
    'Attack': np.random.randint(5, 180, 100),
    'Defense': np.random.randint(5, 230, 100),
    'Sp. Atk': np.random.randint(10, 180, 100),
    'Sp. Def': np.random.randint(20, 230, 100),
    'Speed': np.random.randint(5, 180, 100),
    'Other_Feature': np.random.rand(100) # Example of another feature not used for correlation
}
df = pd.DataFrame(data)

print("Synthetic DataFrame head:")
display(df.head())

# Select the features for correlation analysis
features = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
selected_df = df[features]

# Calculate Pearson correlation coefficient
pearson_corr = selected_df.corr(method='pearson')

plt.figure(figsize=(8, 6))
sns.heatmap(pearson_corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Pearson Correlation Matrix')
plt.show()

# Calculate Spearman rank correlation coefficient
spearman_corr = selected_df.corr(method='spearman')

plt.figure(figsize=(8, 6))
sns.heatmap(spearman_corr, annot=True, cmap='viridis', fmt=".2f", linewidths=.5)
plt.title('Spearman Rank Correlation Matrix')
plt.show()