# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jN7jb2m2K2AwBsG7OQriKAO_suySRO6E
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Au_nanoparticle_dataset.csv')

# Create a new DataFrame by filtering the specified columns
filtered_df = df[['N_total', 'N_bulk', 'N_surface', 'R_avg']]

# Display the head of the new DataFrame
print("Original DataFrame head:")
print(df.head())
print("\nFiltered DataFrame head:")
print(filtered_df.head())

print("First 20 samples of the filtered DataFrame:")
print(filtered_df.head(20))

# Calculate mean, standard deviation, and quartile values for the filtered features
descriptive_stats = filtered_df.describe()

# Display the descriptive statistics
print("Descriptive statistics for N_total, N_bulk, N_surface, and R_avg:")
print(descriptive_stats)

import matplotlib.pyplot as plt
import seaborn as sns

# Set up the figure and axes for a 1x4 layout
fig, axes = plt.subplots(1, 4, figsize=(20, 5))

# Plot histogram for N_total
sns.histplot(filtered_df['N_total'], kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Distribution of N_total')
axes[0].set_xlabel('N_total')
axes[0].set_ylabel('Frequency')

# Plot histogram for N_bulk
sns.histplot(filtered_df['N_bulk'], kde=True, ax=axes[1], color='lightcoral')
axes[1].set_title('Distribution of N_bulk')
axes[1].set_xlabel('N_bulk')
axes[1].set_ylabel('Frequency')

# Plot histogram for N_surface
sns.histplot(filtered_df['N_surface'], kde=True, ax=axes[2], color='lightgreen')
axes[2].set_title('Distribution of N_surface')
axes[2].set_xlabel('N_surface')
axes[2].set_ylabel('Frequency')

# Plot histogram for R_avg
sns.histplot(filtered_df['R_avg'], kde=True, ax=axes[3], color='gold')
axes[3].set_title('Distribution of R_avg')
axes[3].set_xlabel('R_avg')
axes[3].set_ylabel('Frequency')

# Adjust layout to prevent overlapping titles/labels
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Create a pairplot of the filtered_df
sns.pairplot(filtered_df)
plt.suptitle('Pairplot of N_total, N_bulk, N_surface, and R_avg', y=1.02) # Add a main title
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# new_df should be filtered_df based on the previous steps
g = sns.PairGrid(filtered_df)

# Plots on the diagonal contains the histogram of each feature along with the kernel density estimation plot.
g.map_diag(sns.histplot, kde=True)

# Plots on the lower half contains the bivariate kernel density estimation plot.
g.map_lower(sns.kdeplot)

# For the upper half, we will use bivariate histogram as suggested in the original snippet.
g.map_upper(sns.histplot)

# Add a main title
plt.suptitle('Customized Pairplot of N_total, N_bulk, N_surface, and R_avg', y=1.02)

# Display the plot
plt.show()